import React, { useEffect } from 'react'
import { Icon, Panel, Button, PanelGroup, Grid, Row, Col, Divider } from 'rsuite'
import ReactPlayer from "react-player";
import './document.css'
import rs1 from '../../resources/rs1.png';
import rs2 from '../../resources/rs2.gif';
import { useHistory } from 'react-router-dom';


const Documentation = () => {
    let history = useHistory();

    useEffect(() => {

    })


    return (
        <div className="container">

            <Grid fluid>
                <Row gutter={14}>
                    <Col xs={24} md={12}>
                        <p className="document-title">Earn Rewards by staking coins and fiat</p>
                        <p className="document-content">Staking is a great way to maximize your holdings in staking coins and fiat that would otherwise be sitting in your account. Once you have staked your assets you can earn staking rewards on top of your holdings and grow them further by compounding those future rewards.</p>
                        <Button className="bg-highlight get-started" onClick={() => { history.push('/staking')}}>Get Started</Button>
                    </Col>
                    <Col xs={24} md={12} className="col-step">
                    <ReactPlayer
                        url="https://www.youtube.com/watch?v=M3EFi_POhps"
                        width="100%"
                    />
                    </Col>
                </Row>
            </Grid>


            <Grid fluid className="step-grid">
                <Row gutter={14}>
                    <Col md={8} xs={24} className="col-step">
                        <Icon className="highlight" icon="edit" size={"4x"} />
                        <p className="step-title">1. Sign Up & Request the Staking Contract</p>
                        <p className="step-content">Fill in your details and upload the required identity documents. Request and sign the staking contract.</p>
                    </Col>
                    <Col md={8} xs={24} className="col-step step2">
                        <Icon className="highlight" icon="exchange" size={"4x"} />
                        <p className="step-title">2. Fund Your Account</p>
                        <p className="step-content">After successful onboarding, you can fund your account via bank or crypto transfer.</p>
                    </Col>
                    <Col md={8} xs={24} className="col-step">
                        <Icon className="highlight" icon="money" size={"4x"} />
                        <p className="step-title">3. Start Earning</p>
                        <p className="step-content">Start earning staking rewards directly in your Bitcoin Suisse Online Account.</p>
                    </Col>

                </Row>
            </Grid>

            <Grid fluid>
                <Row gutter={14} style={{marginBottom:30}}>
                    <Col md={12} xs={24}>
                        <p className="document-title">
                            What are staking rewards?
                </p>
                        <p className="document-content">
                            You can earn rewards when you stake cryptocurrencies and fiat for a period of time as an incentive to acquire and hold onto staking assets. Some staking coins may require a bonding period. To earn staking rewards, simply select the asset you wish to stake and once it has finished bonding, it will be ready to start staking and earning rewards twice a week from the Proof of Stake process.
                </p>
                    </Col>

                    <Col md={12} xs={24}>
                        <p className="document-title">What is Proof of Stake?</p>
                        <p className="document-content">Popular coins like Bitcoin are proof of work, meaning they’re generated by using machines competing to solve complex equations to “mine” coins and digital assets. Proof of Stake works differently by choosing from a pool of people holding the Proof of Stake coin. A Proof of Stake “validator node” can be added to the pool by staking coins for a certain period of time, giving Proof of Stake validators a source of income without needing powerful mining hardware.
                   </p>
                    </Col>
                </Row>

                <Row gutter={14}>
                <Col md={12} xs={24}>
                        <p className="document-title">Staking coins & cryptocurrencies</p>
                        <p className="document-content">
                            These are the types of coins and fiat currencies that you can earn rewards on through staking service. For example, staking coins such as Tezos (XTZ) and Cosmos (ATOM) can be purchased on wallet and staked to earn rewards.
                    </p>
                    </Col>

                    <Col md={12} xs={24}>
                        <p className="document-title">
                            On-chain and Off-chain staking
                    </p>
                        <p className="document-content">On-Chain staking allows you to stake your assets with blockchain Proof of Stake protocols such as Tezos, while Off-Chain staking allows you to stake your assets with the Margin Pools. Off-chain staking is available for eligible countries only.</p>
                    </Col>
                </Row>
            </Grid>

            <Grid fluid>
                <Row gutter={14} style={{marginBottom:30}}>
                    <Col xs={24}>
                        <p style={{ textAlign: 'center', marginTop: 30, marginBottom: 30 }} className="document-title">Research article about Staking by Mr Athony Vo - CFO KardiaChain</p>
                    </Col>
                    <Col md={12} xs={24}>
                        <p className="document-title">Mainnet — The value of staking</p>
                        <p className="document-content">In this report, Mr Vo provides a thorough overview of a valuation framework in cryptocurrency staking contract that is built upon the Stock Option Theory. Through this report, crypto holders will be provided with a thorough view of a tool to fairly compare between blockchain projects as well as their offering staking rates. Furthermore, such a tool is needed to allow investors to know whether the rate they are receiving is fair to account for potential risk/movement in the underlying tokens. …</p>
                        <Button className="bg-highlight get-started" onClick={() => { window.open('https://medium.com/@KardiaChain/mainnet-the-value-of-staking-a88bc4676a08', '_blank')}}>Learn More</Button>
                    </Col>
                    <Col md={12} xs={24} className="col-step">
                    <img src={rs1} style={{width:'100%'}}/>
                    </Col>
                    
                </Row>

                <Row gutter={14}>
                <Col md={12} xs={24}>
                        <p className="document-title">Mainnet — Part 2. Estimation of KAI Staking APR</p>
                        <p className="document-content">Over the past two years, our incredible developers have been building the Kardiachain mainnet platform and in Q4 we will finally see it go live. Based on the framework that we have developed in the first report — “Mainnet — The value of staking”, Today, we would like to offer the second report on this subject — “Estimation of KAI Staking APR” by KardiaChain CFO Anthony Vo, to give you a better understanding of how the team evaluates staking models and attempt to gauge the potential APR % rates that our model may offer.</p>
                        <Button className="bg-highlight get-started" onClick={() => { window.open('https://medium.com/@KardiaChain/mainnet-part-2-estimation-of-kai-staking-apr-2bb53774be16', '_blank')}}>Learn More</Button>
                    </Col>
                    <Col md={12} xs={24} className="col-step">
                    <img src={rs2} style={{width:'100%'}}/>
                    </Col>
                </Row>
            </Grid>

            <Grid fluid>
                <Row gutter={14}>
                    <Col xs={24}>
                        <p style={{ textAlign: 'center', marginTop: 30, marginBottom: 30 }} className="document-title">FAQ</p>
                    </Col>
                    <Col md={12} xs={24} className="faq-infor">
                        <p className="document-title">Frequently Asked Questions</p>
                        <p className="document-content">Still have questions? Don’t worry, we’re here to help. You can speak directly to an account manager today.</p>
                        <p className="document-content">Phone: 0123 45 67 89</p>
                        <p className="document-content">Email: hello@kardiachain.io</p>
                    </Col>

                    <Col md={12} xs={24}>
                        <PanelGroup accordion bordered>
                            <Panel header="Do I Need to Deposit Funds on Wallet to Stake?">
                                <p className="document-content faq">Yes. To stake with us, you either need to buy XTZ on our exchange or transfer XTZ you already own to Kai from one of your wallets.</p>
                            </Panel>
                            <Panel header="How Much Does Kai Pay in Staking Rewards?">
                                <p className="document-content faq">At 6% compounded annually, we offer the highest fixed-rate returns in the industry.</p>
                            </Panel>
                            <Panel header="When Do I Get My Rewards?">
                                <p className="document-content faq">Unlike other staking services, you start earning rewards within minutes of staking your funds. Payouts happen twice a week – every Monday and Thursday at 14:00 UTC.</p>
                            </Panel>
                            <Panel header="What Fees Do You Charge for Staking?">
                                <p className="document-content faq">Our fee can vary based on the rewards that we earn on behalf of our clients each month. The important point to remember is that our fixed rewards are net any fees that we charge. </p>
                            </Panel>
                            <Panel header="Couldn’t I Stake Myself for Free?">
                                <p className="document-content faq">While you are certainly able to stake yourself, that process can be complex, and you will not have the flexibility to instantly unstake and trade your funds.</p>
                            </Panel>
                        </PanelGroup>
                    </Col>
                </Row>
            </Grid>

        </div>

    )
}

export default Documentation