import React, { useState } from 'react'
import { Icon, Input } from 'rsuite'
import { renderHashToRedirect } from '../../../../common'

export default function CompilerOutput() {
    const [contractName, setContractName] = useState('');
    const [byteCode, setByteCode] = useState('');
    const [abi, setABI] = useState('');

    return (
        <div>
            <p className="color-white text-bold">Compiler debug log:</p>
            <p className="color-white"> <span className="container-icon-left">
                <Icon icon="ok-circle" className="gray-highlight" />
            </span> Note: Contract was created during TxHash# {renderHashToRedirect({
                hash: '0x2ed923eac05e4ef474fca244721d1e86e49535a340537f751b0a63f735b8f942',
                headCount: 80,
                tailCount: 4,
                showTooltip: false,
                redirectTo: `/tx/0x2ed923eac05e4ef474fca244721d1e86e49535a340537f751b0a63f735b8f942`,
                showCopy: false
            })}</p>
            <p className="color-white">
                <span className="container-icon-left">
                    <Icon icon="thumbs-up" className="gray-highlight" />
                </span> <span style={{color:'#36d536'}}>Successfully generated ByteCode and ABI for Contract Address</span> [{renderHashToRedirect({
                    hash: '0x0c2fcf8836e1652448b58080679101f819681b6d',
                    headCount: 80,
                    tailCount: 4,
                    showTooltip: false,
                    redirectTo: `/address/0x0c2fcf8836e1652448b58080679101f819681b6d`,
                    showCopy: false
                })}]</p>
            <p className="color-white">Compiler Version: v0.8.1+commit.df193b15</p>
            <p className="color-white">Optimization Enabled: 0</p>
            <p className="color-white" style={{ marginBottom: 16 }}>Runs: 200</p>

            <div className="row" style={{ marginBottom: 16 }}>
                <p className="color-white text-bold rs-control-label">ContractName:</p>
                <Input
                    rows={5}
                    className="input"
                    value={contractName}
                />
            </div>

            <div className="row" style={{ marginBottom: 16 }}>
                <p className="color-white text-bold rs-control-label">Contract Bytecode:</p>
                <Input
                    componentClass="textarea"
                    rows={5}
                    className="input"
                    value={byteCode}

                />
            </div>

            <div className="row">
                <p className="color-white text-bold rs-control-label">ContractABI:</p>
                <Input
                    componentClass="textarea"
                    rows={5}
                    className="input"
                    value={abi}
                />
            </div>
        </div>
    )
}
